### ISSUE TITLE
Provide some configuration samples for mounting my own configuration

### ISSUE THREAD

**Issue by bwa** [4gsim/activemq-artemis#1]
Find it hard to understand how I would provide my own config. Can you provide some examples ?

**Comment by 4gsim** [comment]
You must create a local folder on the host machine and put the config files (broker.xml, etc.) there, for example **/opt/artemis/config**. Afterwards you start the container while mounting that folder in **/var/lib/artemis-instance/etc-overrides**, for example **-v /opt/artemis/config:/var/lib/artemis-instance/etc-overrides**.
